# SOPS configuration for NixOS secrets
#
# SETUP:
# 1. Generate an age key: age-keygen -o ~/.config/sops/age/keys.txt
# 2. Copy the public key (age1...) and replace the placeholder below
# 3. Create secrets: sops secrets/secrets.yaml
# 4. Enable sops.nix in hosts/adrasteia/default.nix

keys:
  # Add your age public key here (from ~/.config/sops/age/keys.txt)
  - &lia age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *lia
