# This file will be generated by nixos-generate-config during installation.
# Run: sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix
# Then copy the output here.
#
# IMPORTANT: After running nixos-generate-config, copy the hardware-configuration.nix
# content here, but REMOVE the filesystems and boot.* sections since those are
# handled by disk-config.nix and boot.nix respectively.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Kernel modules needed for boot
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Hardware detection
  hardware.enableRedistributableFirmware = true;

  # NOTE: After installation, run nixos-generate-config and update this file
  # with the actual hardware configuration for your system.
}
